name: Publish GTFS

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
  schedule:
    - cron: "43 20 * * 4,0" # Sunday = 0, Thursday = 4

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out